basic:
    name: 'Health Education England (Migration project)'
    environments:
        production: 'https://www.hee.nhs.uk/'
        staging: 'https://hee-d10-stg.uat.rroom.net/'
        development: ''
    basicAuth:
        staging: { user: webadmin, password: rE9ZkDOC5l }
    breakpoints:
        - 350
        - 1200
    pages:
        - /node/4448
        - /node/5142
        - /node/5651
        - /node/5929
        - /node/6015
        - /node/6565
        - /node/5783
        - /node/6582
        - /node/8075
        - /node/8055
        - /node/7547
        - /node/5562
        - /node/8196
        - /node/6091
        - /node/7814
        - /node/8327
        - /node/8357
        - /node/8361
        - /node/8474
        - /node/6507
        - /node/8674
        - /node/8673
        - /node/8670
        - /node/8242
        - /node/8400
        - /node/6866
        - /node/8858
        - /node/8860
        - /node/8864
        - /node/6580
        - /node/6578
        - /node/6668
        - /node/8912
        - /node/8060
        - /node/8061
        - /node/8925
        - /node/8942
        - /node/7245
        - /node/6127
        - /node/6099
        - /node/6844
        - /node/5662
        - /node/7083
        - /node/7138
        - /node/7096
        - /node/7274
        - /node/7281
        - /node/7283
        - /node/7270
        - /node/7271
        - /node/7272
        - /node/7273
        - /node/7277
        - /node/7278
        - /node/7279
        - /node/7280
        - /node/7282
        - /node/7275
        - /node/7276
        - /node/7340
        - /node/5569
        - /node/5431
        - /node/7593
        - /node/6682
        - /node/6165
        - /node/7660
        - /node/7539
        - /node/7607
        - /node/7107
        - /node/7540
        - /node/7110
        - /node/7801
        - /node/8076
        - /node/7631
        - /node/7671
        - /node/7605
        - /node/7113
        - /node/7584
        - /node/7142
        - /node/7143
        - /node/7144
        - /node/8130
        - /node/7122
        - /node/7123
        - /node/7785
        - /node/7639
        - /node/7787
        - /node/7797
        - /node/7719
        - /node/7617
        - /node/8198
        - /node/7972
        - /node/8199
        - /node/7732
        - /node/8167
        - /node/8169
        - /node/8254
        - /node/7642
        - /node/8358
        - /node/8355
        - /node/8164
        - /node/8479
        - /node/8477
        - /node/8475
        - /node/8476
        - /node/8020
        - /node/8467
        - /node/8582
        - /node/8581
        - /node/8161
        - /node/8501
        - /node/8584
        - /node/8583
        - /node/8645
        - /node/8694
        - /node/8580
        - /node/8258
        - /node/8677
        - /node/8676
        - /node/8722
        - /node/7324
        - /node/7478
        - /node/7323
        - /node/7254
        - /node/8696
        - /node/6787
        - /node/7293
        - /node/8730
        - /node/5558
        - /node/8689
        - /node/8733
        - /node/7372
        - /node/7289
        - /node/7291
        - /node/7445
        - /node/7553
        - /node/7640
        - /node/8654
        - /node/8780
        - /node/7641
        - /node/8731
        - /node/8781
        - /node/6131
        - /node/7247
        - /node/5877
        - /node/6129
        - /node/8728
        - /node/8732
        - /node/8930
        - /node/7377
        - /node/8727
        - /node/8212
        - /node/6274
        - /node/7380
        - /node/8399
        - /node/5377
        - /node/9025
        - /node/5015
        - /node/7375
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: "header[class='header ']\ndiv[id=\"block-hee-breadcrumbs\"]\nfooter[class='footer']\nsection#nhse-global-menu\nsection[id='nhse-global-menu']\ndiv[id='cookie-banner']\nsection[class=\"headerSeparator\"]\ndiv[class='breadcrumb']\nfooter[class]"
    remove: "header[class='header ']\ndiv[id=\"block-hee-breadcrumbs\"]\nfooter[class='footer']\nsection#nhse-global-menu\nsection[id='nhse-global-menu']\ndiv[id='cookie-banner']\nsection[class=\"headerSeparator\"]\ndiv[class='breadcrumb']\nfooter[class]"
    delay: 15
    scroll: true
    headers: {  }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: {  }
    sensitivity: 30
    night_mode: false
    retina_images: false
    single_ip: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
