basic:
    name: 'Health Education England (Migration project)'
    environments:
        production: 'https://www.hee.nhs.uk/'
        staging: 'https://hee-d10.stg.uat.rroom.net/'
        development: ''
    basicAuth:
        staging: { user: webadmin, password: rE9ZkDOC5l }
    breakpoints:
        - 350
        - 1200
    pages:
        - /node/8964
        - /node/7439
        - /node/6873
        - /node/6304
        - /node/6419
        - /node/8963
        - /node/6407
        - /node/4462
        - /node/7338
        - /node/7341
        - /node/8729
        - /node/8401
        - /node/6985
        - /node/6982
        - /node/7443
        - /node/6408
        - /node/7349
        - /node/6751
        - /node/7637
        - /node/7385
        - /node/8872
        - /node/7854
        - /node/5854
        - /node/5853
        - /node/7085
        - /node/6630
        - /node/6892
        - /node/4937
        - /node/7339
        - /node/5542
        - /node/8177
        - /node/5193
        - /node/8560
        - /node/8136
        - /node/8744
        - /node/7157
        - /node/4963
        - /node/6162
        - /node/4467
        - /node/5095
        - /node/8402
        - /node/7164
        - /node/5916
        - /node/6337
        - /node/6760
        - /node/5819
        - /node/8633
        - /node/5188
        - /node/8678
        - /node/7753
        - /node/5543
        - /node/5571
        - /node/6852
        - /node/8014
        - /node/4950
        - /node/8405
        - /node/8005
        - /node/6641
        - /node/6688
        - /node/4902
        - /node/4903
        - /node/7104
        - /node/8305
        - /node/6289
        - /node/8499
        - /node/8260
        - /node/8793
        - /node/8394
        - /node/S
        - /node/7379
        - /node/5100
        - /node/7723
        - /node/6276
        - /node/8012
        - /node/8013
        - /node/7407
        - /node/7153
        - /node/8693
        - /node/8692
        - /node/7575
        - /node/8713
        - /node/8397
        - /node/8545
        - /node/8175
        - /node/8591
        - /node/6792
        - /node/6338
        - /node/8538
        - /node/6741
        - /node/6132
        - /node/8445
        - /node/5715
        - /node/5636
        - /node/6791
        - /node/7569
        - /node/8354
        - /node/6513
        - /node/6424
        - /node/6393
        - /node/6979
        - /node/7131
        - /node/4470
        - /node/6295
        - /node/6587
        - /node/5048
        - /node/6598
        - /node/5622
        - /node/6139
        - /node/6058
        - /node/5607
        - /node/5832
        - /node/5704
        - /node/5364
        - /node/5680
        - /node/5509
        - /node/4911
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 15
    scroll: true
    headers: {  }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: {  }
    sensitivity: 5
    night_mode: false
    retina_images: false
    single_ip: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
