basic:
    name: 'Health Education England (Migration project)'
    environments:
        production: 'https://www.hee.nhs.uk/'
        staging: 'https://hee-d10-stg.uat.rroom.net/'
        development: ''
    basicAuth:
        staging: { user: webadmin, password: rE9ZkDOC5l }
    breakpoints:
        - 350
        - 1200
    pages:
        - /node/4448
        - /node/5142
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: "section#nhse-global-menu\nsection[id='nhse-global-menu']\ndiv[class='breadcrumb']\nfooter[class]"
    remove: "section[id='nhse-global-menu']\ndiv[class='breadcrumb']\nfooter[class]"
    delay: 15
    scroll: true
    headers: {  }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: {  }
    sensitivity: 30
    night_mode: false
    retina_images: false
    single_ip: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
